# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Koloda"

  # Pods for Carder

  target 'CarderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarderUITests' do
    # Pods for testing
  end

end
